# Generated by Django 6.0.4 on 2026-05-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_producttransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransactions',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
