# Generated by Django 6.0.4 on 2026-05-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_producttransactions_quantity_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttransactions',
            old_name='quantity_sold',
            new_name='sold',
        ),
    ]
